# Generated by Django 5.2.4 on 2025-07-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название диеты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Диета',
                'verbose_name_plural': 'Диеты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название ингредиента')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Калории (на 100г)')),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Белки (на 100г)')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Жиры (на 100г)')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Углеводы (на 100г)')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('instructions', models.TextField(verbose_name='Инструкция по приготовлению')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Время приготовления (мин)')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Завтрак'), ('LUNCH', 'Обед'), ('DINNER', 'Ужин'), ('SNACK', 'Перекус')], max_length=10, verbose_name='Тип приема пищи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images/', verbose_name='Изображение')),
                ('diets', models.ManyToManyField(related_name='recipes', to='recipes.diet', verbose_name='Подходящие диеты')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_grams', models.PositiveIntegerField(verbose_name='Вес для расчетов (в граммах)')),
                ('display_amount', models.CharField(max_length=50, verbose_name='Количество (отображаемое)')),
                ('display_unit', models.CharField(max_length=50, verbose_name='Единица изм. (отображаемая)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Ингредиент в рецепте',
                'verbose_name_plural': 'Ингредиенты в рецептах',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
