# Generated by Django 5.2.4 on 2025-07-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_servings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet',
            options={'ordering': ['id'], 'verbose_name': 'Диета', 'verbose_name_plural': 'Диеты'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AddField(
            model_name='diet',
            name='carbs_constraint',
            field=models.CharField(choices=[('AT_LEAST', 'Не менее'), ('AT_MOST', 'Не более')], default='AT_LEAST', max_length=10, verbose_name='Ограничение на углеводы'),
        ),
        migrations.AddField(
            model_name='diet',
            name='default_calories',
            field=models.PositiveIntegerField(default=2000, verbose_name='Калории по умолчанию'),
        ),
        migrations.AddField(
            model_name='diet',
            name='percent_carbs',
            field=models.PositiveIntegerField(default=45, verbose_name='Процент углеводов (%)'),
        ),
        migrations.AddField(
            model_name='diet',
            name='percent_fats',
            field=models.PositiveIntegerField(default=25, verbose_name='Процент жиров (%)'),
        ),
        migrations.AddField(
            model_name='diet',
            name='percent_proteins',
            field=models.PositiveIntegerField(default=30, verbose_name='Процент белков (%)'),
        ),
    ]
