# Generated by Django 5.2.4 on 2025-07-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_diet_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='percent_carbs',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='percent_fats',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='percent_proteins',
        ),
        migrations.AddField(
            model_name='diet',
            name='carb_per_1000_kcal',
            field=models.PositiveIntegerField(default=110, verbose_name='Углеводы (г на 1000 ккал)'),
        ),
        migrations.AddField(
            model_name='diet',
            name='fat_per_1000_kcal',
            field=models.PositiveIntegerField(default=40, verbose_name='Жиры (г на 1000 ккал)'),
        ),
        migrations.AddField(
            model_name='diet',
            name='protein_per_1000_kcal',
            field=models.PositiveIntegerField(default=45, verbose_name='Белки (г на 1000 ккал)'),
        ),
    ]
