# Generated by Django 5.2.4 on 2025-07-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_diet_percent_carbs_remove_diet_percent_fats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='diet_icons/', verbose_name='Иконка'),
        ),
    ]
