# Generated by Django 5.2.4 on 2025-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_diet_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_simple_ingredient',
            field=models.BooleanField(default=False, verbose_name='Это простой продукт (не показывать в каталоге)'),
        ),
    ]
